lines = [
    'import { useState } from "react";',
    'import EstateStatusDashboard from "./components/EstateStatusDashboard";',
    '',
    'const OWNER_ADDRESS = "TN5PRWG2ZWPQRKMMF7WOVHRW4WESQHIU7M3OUAAVJ2CLQJRDMGJOHEF2NQ";',
    'const API = "http://localhost:8001";',
    '',
    'function CreateWill({ ownerAddress }: { ownerAddress: string }) {',
    '  const [nominee, setNominee] = useState("");',
    '  const [amount, setAmount] = useState("");',
    '  const [status, setStatus] = useState("");',
    '  const [loading, setLoading] = useState(false);',
    '  const submit = async () => {',
    '    setLoading(true);',
    '    setStatus("Registering will on-chain...");',
    '    try {',
    '      const r = await fetch(API + "/create-will", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ owner_address: ownerAddress, nominee_address: nominee, amount_algo: parseFloat(amount) }) });',
    '      const data = await r.json();',
    '      setStatus("Will created. Tx: " + data.tx_id);',
    '    } catch (e: any) { setStatus("Error: " + e.message); }',
    '    setLoading(false);',
    '  };',
    '  return (',
    '    <div className="rounded-2xl border border-gray-200 bg-white p-6 space-y-4">',
    '      <h2 className="text-base font-medium text-gray-900">Create Digital Will</h2>',
    '      <div className="space-y-3">',
    '        <div>',
    '          <label className="block text-xs text-gray-500 mb-1">Nominee Algorand Address</label>',
    '          <input value={nominee} onChange={e => setNominee(e.target.value)} placeholder="Nominee wallet address" className="w-full border border-gray-200 rounded-lg px-3 py-2 text-xs font-mono focus:outline-none" />',
    '        </div>',
    '        <div>',
    '          <label className="block text-xs text-gray-500 mb-1">ALGO Amount</label>',
    '          <input value={amount} onChange={e => setAmount(e.target.value)} placeholder="1.5" type="number" className="w-full border border-gray-200 rounded-lg px-3 py-2 text-xs focus:outline-none" />',
    '        </div>',
    '        <button onClick={submit} disabled={loading || !nominee || !amount} className="w-full bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white text-sm font-medium py-2 rounded-lg">',
    '          {loading ? "Submitting..." : "Create Will on Algorand"}',
    '        </button>',
    '        {status && <p className="text-xs text-gray-600 break-all">{status}</p>}',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    '',
    'function TriggerDeath({ ownerAddress }: { ownerAddress: string }) {',
    '  const [status, setStatus] = useState("");',
    '  const [loading, setLoading] = useState(false);',
    '  const [txId, setTxId] = useState("");',
    '  const trigger = async () => {',
    '    setLoading(true);',
    '    setStatus("Submitting death event on-chain...");',
    '    try {',
    '      const r = await fetch(API + "/report-death", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ owner_address: ownerAddress }) });',
    '      const data = await r.json();',
    '      setTxId(data.tx_id);',
    '      setStatus("Death reported. Tx: " + data.tx_id.slice(0,10) + "... Will auto-execute in " + data.grievance_seconds + "s.");',
    '    } catch (e: any) { setStatus("Error: " + e.message); }',
    '    setLoading(false);',
    '  };',
    '  return (',
    '    <div className="rounded-2xl border border-red-200 bg-red-50 p-6 space-y-3">',
    '      <h2 className="text-base font-medium text-red-900">Simulate Death Certificate</h2>',
    '      <p className="text-xs text-red-700">In production triggered by DigiLocker CRS API. For demo, press below.</p>',
    '      <button onClick={trigger} disabled={loading} className="w-full bg-red-600 hover:bg-red-700 disabled:opacity-50 text-white text-sm font-medium py-2 rounded-lg">',
    '        {loading ? "Processing..." : "Trigger Death Event"}',
    '      </button>',
    '      {status && <p className="text-xs text-red-800 break-all">{status}</p>}',
    '      {txId && <a href={"https://testnet.algoexplorer.io/tx/" + txId} target="_blank" rel="noreferrer" className="text-xs text-blue-600 underline break-all block">View on Testnet Explorer</a>}',
    '    </div>',
    '  );',
    '}',
    '',
    'export default function App() {',
    '  return (',
    '    <main className="min-h-screen bg-gray-50 p-8">',
    '      <div className="max-w-lg mx-auto space-y-6">',
    '        <div>',
    '          <h1 className="text-2xl font-semibold text-gray-900">Digital Estate Manager</h1>',
    '          <p className="text-sm text-gray-500 mt-1">Self-executing estate transfer on Algorand testnet</p>',
    '        </div>',
    '        <EstateStatusDashboard />',
    '        <CreateWill ownerAddress={OWNER_ADDRESS} />',
    '        <TriggerDeath ownerAddress={OWNER_ADDRESS} />',
    '      </div>',
    '    </main>',
    '  );',
    '}',
]
with open('frontend/src/App.tsx', 'w') as f:
    f.write('\n'.join(lines))
print('Done')